# Generated by Django 5.2.7 on 2026-03-04 23:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELADO'), _negated=True), fields=('data', 'horario_disponivel'), name='unique_data_horario_ativo'),
        ),
    ]
